version: '3.8'

services:
  c5dec: 
    build:
      context: .
      dockerfile: Dockerfile  
    user: root
    container_name: c5dec
    volumes:
      - ./c5dec/assets:/home/root/c5dec/c5dec/assets 
      - ./c5dec/export:/home/root/c5dec/c5dec/export
      - ./c5dec/docs:/home/root/c5dec/c5dec/docs
    ports:
      - 5432:5432
