settings:
  digits: 3
  parent: MRS
  prefix: SRS
  sep: '-'
attributes:
  defaults:
    author: ''
    acceptance: ''
    date: 'DD.MM.YYYY'
    dependence: []
    status: ''
    importance: ''
    urgency: ''
    difficulty: ''
    risk: ''
    outlay: ''
    type: ''
    rationale: ''
    version: ''
  reviewed:
  - author
  - acceptance
  - date
  - dependence
  - status
  - importance
  - urgency
  - risk
  - outlay
  - type
  - rationale
  - version
  publish:
    - author
    - acceptance
    - date
    - dependence
    - status
    - importance
    - urgency
    - risk
    - outlay
    - type
    - rationale
    - version
