settings:
  digits: 3
  itemformat: markdown 
  parent: SRS
  prefix: TSS
  sep: '-'

attributes:
  defaults:
    release: stable 
    header: |
      Add a short description here
    platform: GNU/Linux (Dockerized C5-DEC deployment environment)
    authors: 'AAT'
    execution_type: 'Manual'
    complexity: 1-5
    test_data: see referenced files
    verification_method: 'Test (T)/Review of design (R)/Inspection (I)/Analysis (A)'
    text: |
      ## Preconditions and setup actions
      - 
      
      ## Test steps
      1. follow steps in SRS.
      
      ## Expected outcome
      1.  
    expected_outcome: ''
    version: 1.0
  publish:
  - platform
  - precondition
  - execution_type
  - verification_method
  - release
  - complexity
  - test_data
  - version
  reviewed:
  - authors
  - precondition
  - execution_type
  - verification_method
  - text
