settings:
  digits: 3
  prefix: MRS
  sep: '-'
  itemformat: markdown
attributes:
  defaults:
    type: F
    vm: T
    rationale: See mission analysis
    importance: '3'
    urgency: '3'
    risk: '1'
    difficulty: '1'
    references_content_fingerprint: {}
  reviewed:
  - type
  - vm
  - rationale
  - importance
  - urgency
  - risk
  - difficulty
  publish:
  - type
  - vm
  - rationale
  - importance
  - urgency
  - risk
  - difficulty
