@startuml
skinparam componentStyle rectangle
skinparam linetype ortho
skinparam {
    defaultTextAlignment center
    defaultFontSize 36
    defaultFontName Corbel
}


[\nC5-DEC\n(Common Criteria for Cybersecurity, Crypto, Clouds - Design\nEvaluation and Certification)\n] as c5dec
[\nC5-DEC CAD\n(C5-DEC Computer-Aided Design and Development)\n] as cad
[\nC5-DEC KB\n(C5-DEC Knowledge Base)\n] as kb

c5dec -down- cad
c5dec -down- kb

[\nDesign, Analysis & Development\n(Specifications, Modelling, and \nEvaluation)\n] as dad
[\nCrypto\n(PQC, sign, PGP,\n secret sharing)\n] as crypto
[\nCC Toolbox\n(SFR, SAR, ISO DBs,\n PP, ST, ETR)\n] as cct
[\nPM\n(Project\n Management)\n] as pm
[\n\nISMS\n\n] as isms
[Transformer\n(Import/Export:\ncsv, xlsx, ReqIF,\nXML, md, TeX,\ndocx)] as trafo

cad -down- dad
cad -down- crypto
cad -down- cct
cad -down- pm
cad -down- isms
cad -down- trafo

[\nSSDLC\n(Secure Software Development\nLife Cycle)\n] as ssdlc
[\nSVVM\n(Software Verification and\nValidation Model)\n] as svvm
[\nCPSSA\n(Cyber-Physical System\nSecurity Assessment)\n] as cpssa

kb -down- ssdlc
kb -down- svvm
kb -down- cpssa

[REM\n(Requirement\nEngineering\nand Management)\n] as rem
[\nV&V\n(Verification and\nValidation)\n] as vandv
[Specification\n(Diagrams, code,\nannotations,\nbinaries)\n] as spec
[\nSecurity Analysis\n(Modelling and\nEvaluation)\n] as secana
[\nGeneration Tools\n(Specificaiton,\nKB wiki)\n] as gen
[CC: CEM\n(Tools for\nEvaluation\nMethodology)\n] as cccem
[Resource\nManagement\n(time reports\nconversion,\nconsolidation)] as rm

dad -down- rem
dad -down- vandv
dad -down- spec
dad -down- secana
cct -down- gen
cct -down- cccem
pm -down- rm

[Test Management\n(Test cases,\ntest report,\nlinking to\nrequirements)] as tm
[\nTraceability\n(Verification\nmatrix, RTM)\n] as trace
[\nThreat Modelling\n& Analysis\n] as tma
[\nRisk\nManagement\n] as risk

vandv -down- tm
vandv -down- trace
secana -down- tma
secana -down- risk



@enduml