attributes:
  defaults:
    platform: 'WSL/GNU/Linux Ubuntu 20/Linux Ubuntu 22.04'
    roles: ''
    authors: ''
    precondition: ''
    expected_outcome: 'None'
    verification_method: ''
    success_criteria: 'SRS acceptance criteria fulfilled and expected outcome observed.'
    text: |
      ## Setup
      1. None
      ## Test steps
      1. follow steps in SRS.
  publish:
    platform: 'Windows'
    roles: ''
    authors: ''
    precondition: ''
    expected_outcome: ''
    verification_method: ''
  reviewed:
  - authors
  - precondition
  - expected_outcome
  - verification_method
settings:
  digits: 3
  itemformat: yaml
  parent: SRS
  prefix: TST
  sep: '-'
