@startuml
skinparam componentStyle uml1
skinparam linetype ortho

component Core {
  component doorstop {
      component [doorstop core (API)] <<Component>>
      component [doorstop CLI] <<Component>> 
  }
  [CCSAP] --> [SSDLC (artifacts, REM, V&V)]
  [CC Toolbox] --> doorstop
  [CC Toolbox] <--> [SSDLC (artifacts, REM, V&V)]
  [SSDLC (artifacts, REM, V&V)] --> doorstop
  
  
  [Cryptography] --> doorstop
  [Transformer] --> [SSDLC (artifacts, REM, V&V)]
  
  [Transformer] -[hidden]left- doorstop
  [Transformer] -[hidden]left- [SSDLC (artifacts, REM, V&V)]
  [CC Toolbox] -[hidden]right- [SSDLC (artifacts, REM, V&V)]
  [CC Toolbox] -[hidden]left- [Cryptography]
}

database DataStore {
  component [Flat-file, NoSQL] <<Component>>
  component [git] <<Component>>
}

component FrontEnd {
  component CLI {
  }
  component TUI {
    component [C5-DEC Mini Apps] <<Component>>
    component [asciimatics] <<Component>>
    
  }
  component GUI {
    component [Open-source viewer\n and editor (VS Code,\n web browser, Zettlr)] <<Component>>
  }
}
component ψ {
    [Search]
    [Graph]
    [Security]
    [Graph] -[hidden]right- [Security]
}

component Foundations {
  [Common]
  [Settings]
}

'--intercomponent relations--
Transformer -down-> DataStore
doorstop -down-> DataStore
GUI -up-> DataStore

interface "<U+0000>" as MVC 
interface "<U+0000>" as PSIint
interface "<U+0000>" as Fint

Core -- MVC
MVC -- FrontEnd
MVC -- FrontEnd

Core -right- PSIint
PSIint -right- ψ
PSIint -[hidden]right- [Graph]

Core -down- Fint
Fint -left- Foundations


'---Force Layout---
ψ -[hidden]down- Foundations
Foundations -[hidden]left- DataStore

@enduml
