## Acronyms

| Abbreviation   | Expansion                                                                               |
|:---------------|:----------------------------------------------------------------------------------------|
| ALab           | itrust Abstractions Lab                                                                 |
| C5-DEC         | Common Criteria for Cybersecurity, Crypto, Clouds - Design, Evaluation and Certification|
| CAD            | Computer-Aided Design/Development                                                       |
| CC             | Common Criteria                                                                         |
| CM             | Configuration Management                                                                |
| CPSSA          | Cyber-Physical System Security Analysis                                                 |
| CyFORT         | Cloud Cybersecurity Fortress of Open Resources and Tools for Resilience (CyFORT)        |
| EAL            | Evaluation Assurance Level                                                              |
| ECSS           | European Cooperation for Space Standardization                                          |
| ESA            | European Space Agency                                                                   |
| ICT            | Information and Communication Technology                                                |
| ITR            | itrust consulting                                                                       |
| OSP            | Organization Security Policies                                                          |
| OWASP          | Open Web Application Security Project                                                   |
| PIM            | Platform Independent Model                                                              |
| PM             | Project Management                                                                      |
| PMP            | Project Management Plan                                                                 |
| RID            | Review Item Discrepancy                                                                 |
| SAMM           | Software Assurance Maturity Model                                                       |
| SAR            | Security Assurance Requirement                                                          |
| SDLC           | Software Development Life Cycle                                                         |
| SDP            | Software Development Plan                                                               |
| SFR            | Security Functional Requirement                                                         |
| SPD            | Security Problem Definition                                                             |
| SSA            | Software Security Assurance                                                             |
| SSAP           | Secure Software Assurance Plan                                                          |
| SSDLC          | Secure SDLC                                                                             |
| ST             | Security Target                                                                         |
| SVVM           | Software Verification and Validation Model                                              |
| TM             | Threat Modelling                                                                        |
| TOE            | Target of Evaluation                                                                    |
| TRL            | Technology Readiness Levels                                                             |
| TSF            | TOE Security Functionality                                                              |
| VVP            | Verification and Validation Plan                                                        |
| WBS            | Work Breakdown Structure                                                                |

: Acronyms {#tbl-acronyms}

## Glossary

| Term | Definition |
|:-----|:-----------|
| CM access control | Set of mechanisms and procedures guaranteeing that only authorised access is granted to configuration items. |
| CM documentation | Set of documents describing how the CM system is defined and used. This encloses handbooks, regulations, documentation of tools used for CM, relation of used tools (if any), and so on. |
| CM list | A document listing all the configuration items for a specific product together with the exact version of each CM item relevant for a specific version of the complete product. This list allows distinguishing the items belonging to the evaluated version of the product. |
| CM plan | A document describing how the CM system is used for a specific project or product. Project team members shall adhere to these conventions during the project. |
| CM system | The set of all procedures and tools (including their documentation) used to maintain configurations of the products during their life-cycles. |
| CM system records | CM output documents produced during the operation of the CM system documenting important activities. E.g., CM item change control forms (recording modifications to a configuration item together with the ID of the person making the changes), CM item access approval forms, CM system logs, etc. |
| Configuration item | An object managed by the CM system during the TOE development. These may be either parts of the TOE or objects related to the development of the TOE like evaluation documents or development tools. CM items may be stored in the CM system directly (for example files) or by reference (for example hardware parts) together with their version. |

: Glossary {#tbl-glossary tbl-colwidths="[27,73]"}